-- Migration 021 (tenant): client portal tokens.
--
-- Adds the portal_tokens table used by the read-only client/promoter portal.
-- Each token grants time-limited, unauthenticated, read-only access to one
-- event's public-facing summary (contract status, payment summary, invoice).
--
-- Tokens are generated by staff, distributed via a signed URL
-- (/portal.html?token=...), and can be individually revoked at any time.

SET NAMES utf8mb4;
SET foreign_key_checks = 0;

CREATE TABLE IF NOT EXISTS `portal_tokens` (
  `id`             INT(11)      NOT NULL AUTO_INCREMENT,
  `event_id`       INT(11)      NOT NULL,
  `token`          VARCHAR(128) NOT NULL,
  `label`          VARCHAR(255) DEFAULT NULL COMMENT 'e.g. "Sent to promoter Jane Smith"',
  `created_by_id`  INT(11)      DEFAULT NULL,
  `expires_at`     DATETIME     NOT NULL,
  `last_used_at`   DATETIME     DEFAULT NULL,
  `use_count`      INT(11)      NOT NULL DEFAULT 0,
  `is_revoked`     TINYINT(1)   NOT NULL DEFAULT 0,
  `created_at`     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token` (`token`),
  KEY `event_id` (`event_id`),
  KEY `created_by_id` (`created_by_id`),
  CONSTRAINT `portal_tokens_ibfk_event`    FOREIGN KEY (`event_id`)      REFERENCES `events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `portal_tokens_ibfk_creator`  FOREIGN KEY (`created_by_id`) REFERENCES `users`  (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET foreign_key_checks = 1;
