<?php
declare(strict_types=1);

namespace Panic\Events;

use Panic\BaseEndpoint;
use Panic\Request;
use Panic\Response;
use Panic\Tenant\TenantContext;
use function Panic\log_activity;

/**
 * POST /api/events/{id}/assets/generate-flyer
 *
 * Builds a prompt from the event title, lineup, and description, then
 * delegates to `codex exec` to produce a flyer.png, which is registered
 * as an event asset (approval_status = needs_review).
 *
 * Requires the `upload_assets` capability.
 */
final class GenerateFlyer extends BaseEndpoint
{
    /** Absolute path to the codex binary. */
    private const CODEX_BIN = '/home/cdr/.nvm/versions/node/v22.22.0/bin/codex';

    /** Maximum seconds to wait for codex before giving up. */
    private const TIMEOUT = 180;

    public function handle(Request $request): Response
    {
        if ($request->method() !== 'POST') {
            return Response::methodNotAllowed();
        }
        $eventId = $this->requireEventId();
        if ($denied = $this->requireEventCapability($eventId, 'upload_assets')) {
            return $denied;
        }
        return $this->generate($eventId);
    }

    // -------------------------------------------------------------------------

    private function generate(int $eventId): Response
    {
        $event = $this->db->one(
            'SELECT title, description_public FROM events WHERE id = ?',
            [$eventId]
        );
        if (!$event) {
            return $this->notFound();
        }

        $lineup = $this->db->all(
            "SELECT display_name FROM event_lineup
              WHERE event_id = ? AND status != 'canceled'
              ORDER BY billing_order, set_time",
            [$eventId]
        );

        $prompt = $this->buildPrompt($event, $lineup);

        // Permanent storage: mirror the pattern used in Assets.php
        $filename = time() . '-' . bin2hex(random_bytes(4)) . '-ai-flyer.png';
        $ctx = TenantContext::current();
        if ($ctx !== null) {
            $assetDir = $this->root . '/clients/' . $ctx->tenant['slug'] . '/assets/events/' . $eventId;
            $filePath = 'files/assets/events/' . $eventId . '/' . $filename;
        } else {
            $assetDir = $this->root . '/public/uploads/events/' . $eventId;
            $filePath = 'uploads/events/' . $eventId . '/' . $filename;
        }
        if (!is_dir($assetDir)) {
            mkdir($assetDir, 0775, true);
        }

        // Run codex in an isolated temp directory
        $tmpDir = sys_get_temp_dir() . '/pb-flyer-' . $eventId . '-' . bin2hex(random_bytes(4));
        mkdir($tmpDir, 0700, true);

        try {
            $this->runCodex($prompt, $tmpDir);

            $outFile = $tmpDir . '/flyer.png';
            if (!file_exists($outFile)) {
                return Response::json(['error' => 'Codex completed but did not produce a flyer.png'], 500);
            }

            rename($outFile, $assetDir . '/' . $filename);
        } catch (\RuntimeException $e) {
            return Response::json(['error' => $e->getMessage()], 500);
        } finally {
            // Best-effort cleanup of temp dir
            foreach (glob($tmpDir . '/*') ?: [] as $f) {
                is_file($f) && unlink($f);
            }
            is_dir($tmpDir) && rmdir($tmpDir);
        }

        $assetId = $this->db->insert(
            'INSERT INTO event_assets
                (event_id, asset_type, title, filename, original_filename,
                 file_path, uploaded_by_user_id, approval_status, notes)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)',
            [
                $eventId,
                'flyer',
                'AI-generated flyer',
                $filename,
                'ai-flyer.png',
                $filePath,
                $this->userId(),
                'needs_review',
                'Generated by Codex AI',
            ]
        );

        log_activity($this->db, $eventId, $this->userId(), 'AI flyer generated', ['asset_id' => $assetId]);

        return $this->ok(['id' => $assetId, 'file_path' => $filePath]);
    }

    /**
     * Build the natural-language prompt fed to codex.
     * Pulls title, bands (billing order), and public description.
     */
    private function buildPrompt(array $event, array $lineup): string
    {
        $title = $event['title'];
        $bands = implode(', ', array_column($lineup, 'display_name'));
        $desc  = trim((string) ($event['description_public'] ?? ''));
        if (mb_strlen($desc) > 300) {
            $desc = mb_substr($desc, 0, 300) . '…';
        }

        $prompt  = "Create a square (1:1 ratio) punk rock concert flyer PNG image for an event called \"{$title}\"";
        if ($bands) {
            $prompt .= " featuring {$bands}";
        }
        if ($desc) {
            $prompt .= ". Event description: {$desc}";
        }
        $prompt .= '. The flyer should have bold, high-contrast punk rock poster aesthetics'
                 . ' with striking typography, gritty textures, and vivid colors.'
                 . ' Save the final image as "flyer.png" in the current working directory.';

        return $prompt;
    }

    /**
     * Invoke `codex exec` non-interactively, streaming its output while
     * enforcing a hard timeout. Throws RuntimeException on any failure.
     */
    private function runCodex(string $prompt, string $workingDir): void
    {
        set_time_limit(self::TIMEOUT + 30);

        $cmd = [
            self::CODEX_BIN, 'exec',
            '--skip-git-repo-check',
            '--ephemeral',
            '-C', $workingDir,
            '-s', 'workspace-write',   // allow writes inside the working dir only
            $prompt,
        ];

        // Explicitly supply the cdr user's environment so codex can find its
        // stored OAuth credentials (auth.json) and write its runtime files,
        // regardless of which OS user PHP-FPM is currently running as.
        $env = [
            'HOME'       => '/home/cdr',
            'CODEX_HOME' => '/home/cdr/.codex',
            'PATH'       => dirname(self::CODEX_BIN) . ':/usr/local/bin:/usr/bin:/bin',
            'TMPDIR'     => sys_get_temp_dir(),
            'LANG'       => 'en_US.UTF-8',
        ];

        $descriptors = [
            0 => ['pipe', 'r'],   // stdin
            1 => ['pipe', 'w'],   // stdout
            2 => ['pipe', 'w'],   // stderr
        ];

        $proc = proc_open($cmd, $descriptors, $pipes, $workingDir, $env);
        if (!is_resource($proc)) {
            throw new \RuntimeException(
                'Failed to start codex — ensure it is installed at ' . self::CODEX_BIN
            );
        }

        fclose($pipes[0]);
        stream_set_blocking($pipes[1], false);
        stream_set_blocking($pipes[2], false);

        $stdout = '';
        $stderr = '';
        $start  = time();

        while (true) {
            $read    = [$pipes[1], $pipes[2]];
            $write   = $except = null;
            $changed = @stream_select($read, $write, $except, 1);

            if ($changed === false) {
                break;
            }
            if ($changed > 0) {
                if (in_array($pipes[1], $read, true)) {
                    $chunk = fread($pipes[1], 8192);
                    if ($chunk !== false) {
                        $stdout .= $chunk;
                    }
                }
                if (in_array($pipes[2], $read, true)) {
                    $chunk = fread($pipes[2], 8192);
                    if ($chunk !== false) {
                        $stderr .= $chunk;
                    }
                }
            }

            $status = proc_get_status($proc);
            if (!$status['running']) {
                break;
            }

            if ((time() - $start) >= self::TIMEOUT) {
                proc_terminate($proc);
                fclose($pipes[1]);
                fclose($pipes[2]);
                proc_close($proc);
                throw new \RuntimeException('Codex timed out after ' . self::TIMEOUT . ' seconds');
            }
        }

        fclose($pipes[1]);
        fclose($pipes[2]);
        $exit = proc_close($proc);

        if ($exit !== 0) {
            $detail = trim($stderr) ?: trim($stdout);
            throw new \RuntimeException(
                'Codex exited with code ' . $exit
                . ($detail ? ': ' . mb_substr($detail, 0, 500) : '')
            );
        }
    }
}
