<?php
declare(strict_types=1);

namespace Panic\Events;

use Panic\BaseEndpoint;
use Panic\Request;
use Panic\Response;
use Panic\Tenant\TenantContext;
use function Panic\log_activity;

/**
 * POST /api/events/{id}/assets/generate-flyer
 *
 * Builds a prompt from the event title, lineup, and description, then
 * delegates to `codex exec` to produce a flyer.png, which is registered
 * as an event asset (approval_status = needs_review).
 *
 * Requires the `upload_assets` capability.
 */
final class GenerateFlyer extends BaseEndpoint
{
    /** Absolute path to the codex binary. */
    private const CODEX_BIN = '/home/cdr/.nvm/versions/node/v22.22.0/bin/codex';

    /** Maximum seconds to wait for codex before giving up. */
    private const TIMEOUT = 180;

    public function handle(Request $request): Response
    {
        if ($request->method() !== 'POST') {
            return Response::methodNotAllowed();
        }
        $eventId = $this->requireEventId();
        if ($denied = $this->requireEventCapability($eventId, 'upload_assets')) {
            return $denied;
        }
        return $this->generate($eventId);
    }

    // -------------------------------------------------------------------------

    private function generate(int $eventId): Response
    {
        $event = $this->db->one(
            'SELECT title, description_public FROM events WHERE id = ?',
            [$eventId]
        );
        if (!$event) {
            return $this->notFound();
        }

        $lineup = $this->db->all(
            "SELECT display_name FROM event_lineup
              WHERE event_id = ? AND status != 'canceled'
              ORDER BY billing_order, set_time",
            [$eventId]
        );

        $prompt = $this->buildPrompt($event, $lineup);

        // Permanent storage: mirror the pattern used in Assets.php
        $filename = time() . '-' . bin2hex(random_bytes(4)) . '-ai-flyer.png';
        $ctx = TenantContext::current();
        if ($ctx !== null) {
            $assetDir = $this->root . '/clients/' . $ctx->tenant['slug'] . '/assets/events/' . $eventId;
            $filePath = 'files/assets/events/' . $eventId . '/' . $filename;
        } else {
            $assetDir = $this->root . '/public/uploads/events/' . $eventId;
            $filePath = 'uploads/events/' . $eventId . '/' . $filename;
        }
        if (!is_dir($assetDir)) {
            mkdir($assetDir, 0775, true);
        }

        // Run codex in an isolated temp directory
        $tmpDir = sys_get_temp_dir() . '/pb-flyer-' . $eventId . '-' . bin2hex(random_bytes(4));
        mkdir($tmpDir, 0755, true);

        try {
            $this->runCodex($prompt, $tmpDir);

            // Codex may save images in a generated_images/<uuid>/ subfolder
            // rather than at the root of the working dir, so search recursively.
            $outFile = $this->findFirstPng($tmpDir);
            if ($outFile === null) {
                return Response::json(['error' => 'Codex completed but did not produce a PNG image'], 500);
            }

            rename($outFile, $assetDir . '/' . $filename);
        } catch (\RuntimeException $e) {
            return Response::json(['error' => $e->getMessage()], 500);
        } finally {
            // Best-effort cleanup of temp dir
            $this->rrmdir($tmpDir);
        }

        $assetId = $this->db->insert(
            'INSERT INTO event_assets
                (event_id, asset_type, title, filename, original_filename,
                 file_path, uploaded_by_user_id, approval_status, notes)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)',
            [
                $eventId,
                'flyer',
                'AI-generated flyer',
                $filename,
                'ai-flyer.png',
                $filePath,
                $this->userId(),
                'needs_review',
                'Generated by Codex AI',
            ]
        );

        log_activity($this->db, $eventId, $this->userId(), 'AI flyer generated', ['asset_id' => $assetId]);

        return $this->ok(['id' => $assetId, 'file_path' => $filePath]);
    }

    /** Recursively delete a directory and all its contents. */
    private function rrmdir(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }
        $it = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::CHILD_FIRST
        );
        foreach ($it as $f) {
            $f->isDir() ? rmdir($f->getPathname()) : unlink($f->getPathname());
        }
        rmdir($dir);
    }

    /**
     * Recursively find the first PNG file under $dir.
     * Codex sometimes saves images in generated_images/<uuid>/ subfolders.
     */
    private function findFirstPng(string $dir): ?string
    {
        $it = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS));
        foreach ($it as $file) {
            if ($file->isFile() && strtolower($file->getExtension()) === 'png') {
                return $file->getPathname();
            }
        }
        return null;
    }

    /**
     * Build the natural-language prompt fed to codex.
     * Pulls title, bands (billing order), and public description.
     */
    private function buildPrompt(array $event, array $lineup): string
    {
        $title = $event['title'];
        $bands = implode(', ', array_column($lineup, 'display_name'));
        $desc  = trim((string) ($event['description_public'] ?? ''));
        if (mb_strlen($desc) > 300) {
            $desc = mb_substr($desc, 0, 300) . '…';
        }

        $prompt  = "Create a square (1:1 ratio) punk rock concert flyer PNG image for an event called \"{$title}\"";
        if ($bands) {
            $prompt .= " featuring {$bands}";
        }
        if ($desc) {
            $prompt .= ". Event description: {$desc}";
        }
        $prompt .= '. The flyer should have bold, high-contrast punk rock poster aesthetics'
                 . ' with striking typography, gritty textures, and vivid colors.'
                 . ' Generate exactly one image.';

        return $prompt;
    }

    /** Invoke `codex exec` and wait for it to finish. Throws on non-zero exit. */
    private function runCodex(string $prompt, string $workingDir): void
    {
        set_time_limit(self::TIMEOUT + 30);

        // Codex's in-process app-server needs a writable CODEX_HOME to create
        // its runtime files (sockets, logs). ~/.codex is owned by cdr and not
        // writable by www-data, so we copy auth + config into a temp dir that
        // the current process owns and clean it up when we're done.
        $codexHome = sys_get_temp_dir() . '/codex-home-' . bin2hex(random_bytes(4));
        mkdir($codexHome, 0755, true);
        copy('/home/cdr/.codex/auth.json',   $codexHome . '/auth.json');
        copy('/home/cdr/.codex/config.toml', $codexHome . '/config.toml');

        try {
            $bin = self::CODEX_BIN;
            $cmd = 'HOME=' . escapeshellarg($codexHome)
                 . ' CODEX_HOME=' . escapeshellarg($codexHome)
                 . ' PATH=' . escapeshellarg(dirname($bin) . ':/usr/local/bin:/usr/bin:/bin')
                 . ' ' . escapeshellarg($bin)
                 . ' exec --skip-git-repo-check --ephemeral'
                 . ' -C ' . escapeshellarg($workingDir)
                 . ' -s workspace-write'
                 . ' ' . escapeshellarg($prompt)
                 . ' 2>&1';

            exec($cmd, $lines, $exitCode);

            if ($exitCode !== 0) {
                $detail = implode("\n", array_slice($lines, 0, 20));
                throw new \RuntimeException('Codex failed: ' . mb_substr($detail, 0, 500));
            }
        } finally {
            // Remove the temp codex home (auth copy etc.)
            foreach (glob($codexHome . '/{,.}*', GLOB_BRACE) ?: [] as $f) {
                is_file($f) && unlink($f);
            }
            is_dir($codexHome) && rmdir($codexHome);
        }
    }
}
