<?php

declare(strict_types=1);

namespace Panic;

/**
 * Renders a print-ready PDF for an EXISTING physical ticket batch.
 *
 * Pure and read-only with respect to the database: given a batch id, this
 * loads the batch + its ticket rows + event/venue/tier data and produces PDF
 * bytes. It never writes to `tickets`, `physical_ticket_batches`, or
 * `ticket_types`, and never persists the generated bytes anywhere (no
 * storage/ cache file). That's deliberate, not an optimization left out:
 *
 *   - "Regenerate PDF" and the original "Download PDF" are the SAME code
 *     path (mode/sheet query params only) — regeneration is trivially safe
 *     because it is a pure function of rows that were already fixed at
 *     batch-creation time (same ticket numbers, same tokens, same QR
 *     destinations, every time), with no separate cache to invalidate.
 *   - "Do not create duplicate ticket records if PDF generation is retried"
 *     falls out for free: generation never touches the tickets table at all.
 *
 * Two output modes:
 *   - individual: one page per ticket at exact trim size (+ bleed/crop marks
 *     if requested). The brief calls this the important one — a print shop
 *     can impose it however they like.
 *   - imposed: multiple tickets tiled onto a common sheet size (Letter,
 *     11x17, 12x18) with configurable spacing.
 *
 * Before returning bytes, runs the brief's "Print validation" checks as hard
 * assertions (throws PhysicalTicketValidationException rather than silently
 * emitting a bad PDF) — see validate().
 */
final class PhysicalTicketPdfGenerator
{
    private const SHEETS = [
        'letter' => ['w' => 8.5, 'h' => 11.0],
        '11x17'  => ['w' => 11.0, 'h' => 17.0],
        '12x18'  => ['w' => 12.0, 'h' => 18.0],
    ];

    private const SHEET_MARGIN_IN = 0.25;
    private const SHEET_GUTTER_IN = 0.125;
    /** Extra margin beyond bleed reserved purely for crop-mark lines to live in. */
    private const CROP_MARK_MARGIN_PT = 18.0;
    private const CROP_MARK_LEN_PT = 14.0;
    private const CROP_MARK_GAP_PT = 4.0;

    private PhysicalTicketRenderer $renderer;

    public function __construct(?PhysicalTicketRenderer $renderer = null)
    {
        $this->renderer = $renderer ?? new PhysicalTicketRenderer();
    }

    /**
     * @return array{bytes:string,filename:string,ticket_count:int}
     * @throws \RuntimeException if the batch doesn't exist
     * @throws PhysicalTicketValidationException if the rendered output fails a print-safety check
     */
    public function generate(Database $db, int $eventId, int $batchId, string $mode, string $sheetKey, string $appUrl): array
    {
        $mode = in_array($mode, ['individual', 'imposed'], true) ? $mode : 'individual';
        $ctx = $this->loadContext($db, $eventId, $batchId);

        $pdf = new Pdf();
        $geometries = $mode === 'individual'
            ? $this->renderIndividual($pdf, $ctx, $appUrl)
            : $this->renderImposed($pdf, $ctx, $sheetKey, $appUrl);

        $bytes = $pdf->output();
        $this->validate($bytes, $ctx, $geometries);

        $filename = $this->filename($ctx, $mode, $sheetKey);
        return ['bytes' => $bytes, 'filename' => $filename, 'ticket_count' => count($ctx['tickets'])];
    }

    /**
     * Debug/admin-only validation manifest: {ticket_number, token, url} per
     * ticket. Never bundled into the print PDF itself — a separate JSON
     * endpoint, gated the same as every other batch action (manage_ticketing
     * capability). This app has no separate APP_DEBUG/APP_ENV flag
     * convention to gate behind, so admin auth is the only (and sufficient)
     * gate: the plaintext token is already visible to this same role via the
     * existing ticket-resend/list surfaces in Events/Ticketing.php.
     *
     * @return array<int,array{ticket_number:string,token:string,url:string}>
     */
    public function manifest(Database $db, int $eventId, int $batchId, string $appUrl): array
    {
        $ctx = $this->loadContext($db, $eventId, $batchId);
        $out = [];
        foreach ($ctx['tickets'] as $t) {
            $out[] = [
                'ticket_number' => (string) $t['printed_number'],
                'token'         => (string) $t['token'],
                'url'           => $this->ticketUrl($appUrl, (string) $t['token']),
            ];
        }
        return $out;
    }

    // ── context loading ─────────────────────────────────────────────────────────

    private function loadContext(Database $db, int $eventId, int $batchId): array
    {
        $batch = $db->one(
            'SELECT * FROM physical_ticket_batches WHERE id = ? AND event_id = ?',
            [$batchId, $eventId]
        );
        if ($batch === null) {
            throw new \RuntimeException("Physical ticket batch {$batchId} not found for this event.");
        }

        $event = $db->one(
            'SELECT e.id, e.title, e.slug, e.date, e.doors_time, e.show_time,
                    v.name AS venue_name, v.address AS venue_address, v.city AS venue_city, v.state AS venue_state,
                    r.address AS room_address
               FROM events e
               LEFT JOIN venues v ON v.id = e.venue_id
               LEFT JOIN resources r ON r.id = e.resource_id
              WHERE e.id = ?',
            [$eventId]
        );
        if ($event === null) {
            throw new \RuntimeException("Event {$eventId} not found.");
        }

        $ticketType = $db->one(
            'SELECT id, name, price_cents, currency FROM ticket_types WHERE id = ?',
            [(int) $batch['ticket_type_id']]
        );
        if ($ticketType === null) {
            throw new \RuntimeException('Ticket type for this batch no longer exists.');
        }

        $tickets = $db->all(
            'SELECT id, printed_number, token
               FROM tickets
              WHERE physical_batch_id = ?
              ORDER BY printed_number ASC',
            [$batchId]
        );
        if ($tickets === []) {
            throw new \RuntimeException('This batch has no ticket rows to render.');
        }

        $venue = [
            'name'    => $event['venue_name'] ?? 'Mabuhay Gardens',
            // The room's own address wins over the venue's, matching Address::pick()'s
            // convention used elsewhere (TicketView, TicketingService::emailTickets()).
            'address' => Address::pick($event['room_address'] ?? null, $event['venue_address'] ?? null),
            'city'    => $event['venue_city'] ?? null,
            'state'   => $event['venue_state'] ?? null,
        ];

        return [
            'batch'       => $batch,
            'event'       => $event,
            'ticket_type' => $ticketType,
            'venue'       => $venue,
            'tickets'     => $tickets,
        ];
    }

    private function ticketUrl(string $appUrl, string $token): string
    {
        return rtrim($appUrl, '/') . '/t/' . rawurlencode($token);
    }

    // ── individual mode ─────────────────────────────────────────────────────────

    /** @return array<int,array{ticket:array,geometry:array}> */
    private function renderIndividual(Pdf $pdf, array $ctx, string $appUrl): array
    {
        $batch = $ctx['batch'];
        $widthPt  = Pdf::inchesToPoints((float) $batch['ticket_width_in']);
        $heightPt = Pdf::inchesToPoints((float) $batch['ticket_height_in']);
        $bleedPt  = Pdf::inchesToPoints((float) $batch['bleed_in']);
        $cropMarks = (bool) (int) $batch['crop_marks'];
        $cropMargin = $cropMarks ? self::CROP_MARK_MARGIN_PT : 0.0;

        $marginPt = $bleedPt + $cropMargin;
        $pageW = $widthPt + 2 * $marginPt;
        $pageH = $heightPt + 2 * $marginPt;

        $artworkId = $this->registerArtwork($pdf, $ctx['batch']);

        $geometries = [];
        foreach ($ctx['tickets'] as $ticket) {
            $pdf->beginPage($pageW, $pageH);

            if ($artworkId !== null) {
                // Artwork covers the full bleed box (marginPt in from the
                // crop-mark margin, if any), per "0.125in bleed if artwork
                // extends to the edge".
                $this->renderer->renderArtwork($pdf, $artworkId, $cropMargin, $cropMargin, $widthPt + 2 * $bleedPt, $heightPt + 2 * $bleedPt);
            }

            if ($cropMarks) {
                $this->drawCropMarks($pdf, $marginPt, $marginPt, $widthPt, $heightPt);
            }

            $geometry = $this->renderer->render(
                $pdf, $marginPt, $marginPt, $widthPt, $heightPt,
                $ticket, $batch, $ctx['event'], $ctx['ticket_type'], $ctx['venue'],
                $this->ticketUrl($appUrl, (string) $ticket['token']),
                $artworkId
            );
            $geometries[] = ['ticket' => $ticket, 'geometry' => $geometry];
        }

        return $geometries;
    }

    // ── imposed mode ────────────────────────────────────────────────────────────

    /** @return array<int,array{ticket:array,geometry:array}> */
    private function renderImposed(Pdf $pdf, array $ctx, string $sheetKey, string $appUrl): array
    {
        $sheet = self::SHEETS[$sheetKey] ?? self::SHEETS['letter'];
        $sheetW = Pdf::inchesToPoints($sheet['w']);
        $sheetH = Pdf::inchesToPoints($sheet['h']);

        $batch = $ctx['batch'];
        $widthPt  = Pdf::inchesToPoints((float) $batch['ticket_width_in']);
        $heightPt = Pdf::inchesToPoints((float) $batch['ticket_height_in']);
        $bleedPt  = Pdf::inchesToPoints((float) $batch['bleed_in']);
        $cropMarks = (bool) (int) $batch['crop_marks'];
        $gutterPt = Pdf::inchesToPoints(self::SHEET_GUTTER_IN);
        $marginPt = Pdf::inchesToPoints(self::SHEET_MARGIN_IN);

        $cellW = $widthPt + 2 * $bleedPt + $gutterPt;
        $cellH = $heightPt + 2 * $bleedPt + $gutterPt;
        $usableW = $sheetW - 2 * $marginPt;
        $usableH = $sheetH - 2 * $marginPt;
        $cols = max(1, (int) floor(($usableW + $gutterPt) / $cellW));
        $rows = max(1, (int) floor(($usableH + $gutterPt) / $cellH));
        $perSheet = $cols * $rows;

        $artworkId = $this->registerArtwork($pdf, $batch);

        $geometries = [];
        $tickets = $ctx['tickets'];
        $total = count($tickets);
        for ($offset = 0; $offset < $total; $offset += $perSheet) {
            $pdf->beginPage($sheetW, $sheetH);
            $slice = array_slice($tickets, $offset, $perSheet);
            foreach ($slice as $i => $ticket) {
                $col = $i % $cols;
                $row = intdiv($i, $cols);
                // Sheet origin: bottom margin, working left-to-right / top-to-bottom
                // visually means top row first — row 0 is the TOP row of the sheet.
                $cellX = $marginPt + $col * $cellW;
                $cellY = $sheetH - $marginPt - ($row + 1) * $cellH + $gutterPt;
                $trimX = $cellX + $bleedPt;
                $trimY = $cellY + $bleedPt;

                if ($artworkId !== null) {
                    $this->renderer->renderArtwork($pdf, $artworkId, $cellX, $cellY, $widthPt + 2 * $bleedPt, $heightPt + 2 * $bleedPt);
                }
                if ($cropMarks) {
                    $this->drawCropMarks($pdf, $trimX, $trimY, $widthPt, $heightPt);
                }

                $geometry = $this->renderer->render(
                    $pdf, $trimX, $trimY, $widthPt, $heightPt,
                    $ticket, $batch, $ctx['event'], $ctx['ticket_type'], $ctx['venue'],
                    $this->ticketUrl($appUrl, (string) $ticket['token']),
                    $artworkId
                );
                $geometries[] = ['ticket' => $ticket, 'geometry' => $geometry];
            }
        }

        return $geometries;
    }

    private function drawCropMarks(Pdf $pdf, float $trimX, float $trimY, float $widthPt, float $heightPt): void
    {
        $gap = self::CROP_MARK_GAP_PT;
        $len = self::CROP_MARK_LEN_PT;
        $corners = [
            [$trimX, $trimY],
            [$trimX + $widthPt, $trimY],
            [$trimX, $trimY + $heightPt],
            [$trimX + $widthPt, $trimY + $heightPt],
        ];
        foreach ($corners as [$cx, $cy]) {
            $dirX = $cx <= $trimX + $widthPt / 2 ? -1 : 1;
            $dirY = $cy <= $trimY + $heightPt / 2 ? -1 : 1;
            // Horizontal mark, offset from the trim corner along X, outside the corner.
            $pdf->line($cx + $dirX * $gap, $cy, $cx + $dirX * ($gap + $len), $cy, 0.35);
            // Vertical mark.
            $pdf->line($cx, $cy + $dirY * $gap, $cx, $cy + $dirY * ($gap + $len), 0.35);
        }
    }

    private function registerArtwork(Pdf $pdf, array $batch): ?string
    {
        $path = $batch['artwork_path'] ?? null;
        if ($path === null || $path === '') {
            return null;
        }
        $fullPath = dirname(__DIR__) . '/' . ltrim((string) $path, '/');
        if (!is_file($fullPath)) {
            return null; // missing file on disk — render text-only rather than fail the batch
        }
        $bytes = (string) file_get_contents($fullPath);
        $id = 'batch-artwork-' . (int) $batch['id'];
        $info = @getimagesizefromstring($bytes);
        if ($info !== false && $info[2] === IMAGETYPE_JPEG) {
            return $pdf->addJpegImage($bytes, $id);
        }
        try {
            return $pdf->addPngImage($bytes, $id);
        } catch (\Throwable) {
            return null;
        }
    }

    private function filename(array $ctx, string $mode, string $sheetKey): string
    {
        $eventSlug = (string) ($ctx['event']['slug'] ?? 'event');
        $tierSlug = self::slugify((string) $ctx['ticket_type']['name']);
        $batchId = (int) $ctx['batch']['id'];
        $suffix = $mode === 'individual' ? 'individual' : (self::SHEETS[$sheetKey] ?? null ? $sheetKey : 'letter');
        return "{$eventSlug}-{$tierSlug}-batch-{$batchId}-{$suffix}.pdf";
    }

    private static function slugify(string $s): string
    {
        $s = strtolower(trim($s));
        $s = preg_replace('/[^a-z0-9]+/', '-', $s) ?? '';
        return trim($s, '-') ?: 'tickets';
    }

    // ── print validation ────────────────────────────────────────────────────────

    /**
     * Hard assertions from the brief's "Print validation" section. Any
     * failure throws rather than letting a bad PDF out the door.
     *
     * @param array<int,array{ticket:array,geometry:array}> $geometries
     */
    private function validate(string $bytes, array $ctx, array $geometries): void
    {
        if (!str_starts_with($bytes, '%PDF-')) {
            throw new PhysicalTicketValidationException('Generated output is not a valid PDF (missing header).');
        }
        if (!str_contains(substr($bytes, -32), '%%EOF')) {
            throw new PhysicalTicketValidationException('Generated output is not a valid PDF (missing trailer).');
        }

        $tickets = $ctx['tickets'];
        $expectedCount = count($tickets);

        // Quantity generated == requested.
        if (count($geometries) !== $expectedCount) {
            throw new PhysicalTicketValidationException(
                "Rendered {$this->pluralCount(count($geometries))} but the batch has {$expectedCount}."
            );
        }

        // Every printed_number and token unique (within this batch — the DB's
        // own UNIQUE constraints are the cross-batch/cross-event authority;
        // this is a defense-in-depth check on what we're about to hand out).
        $numbers = array_map(static fn(array $t): string => (string) $t['printed_number'], $tickets);
        if (count($numbers) !== count(array_unique($numbers))) {
            throw new PhysicalTicketValidationException('Duplicate ticket numbers detected in this batch.');
        }
        $tokens = array_map(static fn(array $t): string => (string) $t['token'], $tickets);
        if (count($tokens) !== count(array_unique($tokens))) {
            throw new PhysicalTicketValidationException('Duplicate QR tokens detected in this batch.');
        }

        // Ticket numbers fall within the batch's declared range.
        $first = (int) $ctx['batch']['first_ticket_number'];
        $last  = (int) $ctx['batch']['last_ticket_number'];
        foreach ($numbers as $numStr) {
            $n = (int) ltrim($numStr, '0');
            $n = $numStr === str_repeat('0', strlen($numStr)) ? 0 : $n;
            if ($n < $first || $n > $last) {
                throw new PhysicalTicketValidationException("Ticket #{$numStr} falls outside the batch's declared range #{$first}\xE2\x80\x93#{$last}.");
            }
        }

        // QR geometry: stays within the trim box, and keeps its quiet zone.
        $minQuiet = PhysicalTicketRenderer::minQuietZonePt();
        foreach ($geometries as $g) {
            $trim = $g['geometry']['trim_box'];
            $qr   = $g['geometry']['qr_box'];
            if ($qr['x'] < $trim['x'] - 0.01 || $qr['y'] < $trim['y'] - 0.01
                || $qr['x'] + $qr['w'] > $trim['x'] + $trim['w'] + 0.01
                || $qr['y'] + $qr['h'] > $trim['y'] + $trim['h'] + 0.01
            ) {
                throw new PhysicalTicketValidationException(
                    "Ticket #{$g['ticket']['printed_number']}'s QR code extends outside the printable ticket area."
                );
            }
            if ($g['geometry']['quiet_zone_pt'] < $minQuiet) {
                throw new PhysicalTicketValidationException(
                    "Ticket #{$g['ticket']['printed_number']}'s QR quiet zone is too small to scan reliably."
                );
            }
        }
    }

    private function pluralCount(int $n): string
    {
        return $n . ' ticket' . ($n === 1 ? '' : 's');
    }
}

/** A generated batch PDF failed one of the print-safety checks — see PhysicalTicketPdfGenerator::validate(). */
final class PhysicalTicketValidationException extends \RuntimeException
{
}
